/*
Author: Denegan Ichwen
Last update: 18/08/24
Description: Function that takes a positive integer and prints on console
a  table where each cell is the product generated by the multiplication
of its respective row and column.
*/

#include <stdio.h>

void printMultiplicationTable(int size)
{
    int i = 0;
    
    printf("  ");

    for (; i <= size; i++)
    {
        printf("%d ", i);
    }
    printf("\n");

    for (i = 0; i <= size; i++)
    {
        printf("%d ", i);

        for (int j = 0; j <= size; j++)
        {
            printf("%d ", i * j);
        }
        printf("\n");
    }
}

int main()
{
    int size;

    printf("Enter the size of the multiplication table: ");
    scanf("%d", &size);

    printf("La tabla de multiplication es:\n\n");
    printMultiplicationTable(size);
    printf("\n");

    return 0;
}